//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNICAH.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaseDia
    {
        public int Id { get; set; }
        public int FkClasePeriodoId { get; set; }
        public byte FkDiaId { get; set; }
    
        public virtual ClasePeriodo ClasePeriodo { get; set; }
        public virtual Dias Dias { get; set; }
    }
}
