//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNICAH.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClasePeriodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClasePeriodo()
        {
            this.ClaseDia = new HashSet<ClaseDia>();
        }
    
        public int Id { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
        public short FKMaestroId { get; set; }
        public int FKPeriodoId { get; set; }
        public int FKClaseId { get; set; }
        public short FkAulaId { get; set; }
        public string Dias { get; set; }
    
        public virtual Aulas Aulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaseDia> ClaseDia { get; set; }
        public virtual Clases Clases { get; set; }
        public virtual Maestros Maestros { get; set; }
        public virtual Periodos Periodos { get; set; }
    }
}
